spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    lease-expiration-duration-in-seconds: 20


management:
  endpoints:
    refresh:
      enabled: true
    web:
      exposure:
        include: '*'
