server:
  port: 8200

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: searchModule
          uri: lb://search-service
          predicates:
            - Path=/search/**

        - id: detailsModule
            uri: lb://details-service
            predicates:
              - Path=/details/**

        - id: provideModule
            uri: lb://provider-service
            predicates:
              - Path=/provider/**

      # open lb
      discovery:
        locator:
          enabled: true

myservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 10


management:
  endpoints:
    refresh:
      enabled: true
    web:
      exposure:
        include: '*'
