spring:
  application:
    name: provider-service

  # configure h2 in-memory database
  datasource:
    url: jdbc:h2:~/test
    username: root
    password: 12345
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true


server:
  port: 9124


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 10


management:
  endpoints:
    refresh:
      enabled: true
    web:
      exposure:
        include: '*'
