#config datasource
spring:
  application:
    name: university-service

  datasource:
#    TODO: NEED ENCRYPT HERE
    url: '{cipher}AQB7CS6kkqFm3baqQNtu2AOpLMWTK1TFL9/ZWKiD/2PI6CjCgwfUwZPc0C/ZbnBY19/Yx2uyq74i/LU1C2V3Aw+lciuP/aacmuOw4XKb+j9i0dgUYqEb+f7t5UhNCAuG2qKo3zqCtNYMCDkR91UcZ1awHrCV3gNqjorhYGMguxnxebHo5qv3BYvn75AdlZ7E0vosUHc0k0mgFX/leftECyGDmDACP3exmwiWrEKN5fiy11reFxcm8JwPwiu/BIq1nYfSss+7Reo4ZqkKjsGIFiGxKPnhJnkjnukG8oWoiUmrbhIf0J3JkvDFgd7a2oKpibPA0pGlZk/Od148n9c0aq5N3+yCSFCCbmGGArXjQzii584OZvQUlLeo61IB77mCwaZQi+qOuASK1Rwz3S3sx6S3ATQ6mosY1BNjLdaIXSeSoQ=='
    username: '{cipher}AQA9wqVPCXAgX46fUJCwLOzI6eUCcO/KrE0XAZZYVAwomt2B9JHZnorODMa8Kbz2wQjALXfc4UJ855SMLBJkoQlrzQQICLZyAZVzrvjHHa7j/kHqQEu/4ZST4flQmN7XdMLqGK8dawmq1MLIGD1HmD3WVt9v47oxDpOqNMZzVYLjhVf6xkCDQnOSWPf8SD2HfC7vKedAbsVVPu25bIupAt7lGjXlDEGX6kuJmPbM5K44INzD6Uq2fIytHGpMlJ07nKF1IP+luzHYFIxRmFr8hpZpMm3RsCPQif/u1JJk8uW7AuYeLzcHQqTkIjOB6iq6v3hagMmCS8WBFEP/JMNOnpWEbEtAV7V2gEOl2mSrrmHdjarF9uPTlZpfvN6+IIHC408='
    password: 'AQAl+jqK3aYEOVqHgsK95V0WAhbpkoxmKuSHobZ+w+4g3RT70sjqdp7Itj+OhfVvJwNpK9JHihMedSZSv+26M5D/ph3UWYbp2tMz7RCIztkEzRVCQlKZ3FZ3N8Rz28xEQ3qnudjTBOR4aUSf1OysXAT8FvpnjTDaRa3WnCO7H6J9Qg9dOxLV6nwWNBuPgpVUEQyMU0iS1A+HGy7s5z4x1lsLMWKuZikw5pYbPEypP/Kj3oiBl8sJgHd2I+cZbNfbvRRczd1fMd9tIlTBoNCrpFDKDfAK+Q5GMuzkNU9bmNO/e5NzE5z6Sfzckrh4KkglIZO9lBm78KH0I4C3tykRlb4NF47CSvn2BiN0m5P1t/peK2rnd27QUIlT6k8AbxdGfzU='
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

server:
  port: 7683

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://localhost:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 10


management:
  endpoints:
    refresh:
      enabled: true
    web:
      exposure:
        include: '*'


